version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - REDISCLOUD_URL=redis:6379
    ports:
      - '8000:8000'
    depends_on:
      - redis
    volumes:
      - .:/usr/src/node-app
    networks:
      - elk

  redis:
    image: redis:6.0.6
    volumes:
      - ./redis/data:/data
    networks:
      - elk
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes

volumes:
  dbdata:

networks:
  elk:
    driver: bridge
